version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    # expose Redis on the host, AND also make it join our k6-net
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    # allow Redis to open tons of FDs
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    # bump in-container kernel settings for TCP backlogs & port recycling
    sysctls:
      net.core.somaxconn: '65535'
      net.ipv4.tcp_max_syn_backlog: '65535'
      net.ipv4.ip_local_port_range: '10000 65000'
      net.ipv4.tcp_tw_reuse: '1'
      net.ipv4.tcp_fin_timeout: '30'
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  redis-data:
  prometheus-data:
  grafana-storage:
