apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

    jsonData:
      timeInterval: 1s        # This is the 'Scrape interval' setting (suggests $__interval)
      interval: "step"         # This sets 'Interval behavior': options = step | range | no-default
