{
 "title": "Leaderboard Repository: Redis / Caffeine / Java",
 "tags": [
  "leaderboard",
  "micrometer",
  "performance"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "type", "label": "Implementation", "query": "caffeine,java,redis" }
  ]
 },
 "panels": [
  {
   "title": "Increment Score Latency (p50/p95/p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(leaderboard_increment_score_seconds_bucket[2s])) by (le,type))* 1000",
     "legendFormat": "p50 ({{type}})"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(leaderboard_increment_score_seconds_bucket[2s])) by (le,type))* 1000",
     "legendFormat": "p95 ({{type}})"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(leaderboard_increment_score_seconds_bucket[2s])) by (le,type))* 1000",
     "legendFormat": "p99 ({{type}})"
    }
   ]
  },
  {
   "title": "Increment Score Throughput (ops/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(leaderboard_increment_score_seconds_count[2s])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Get Top Players Latency (p50/p95/p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(leaderboard_get_top_players_seconds_bucket[2s])) by (le,type))* 1000",
     "legendFormat": "p50 ({{type}})"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(leaderboard_get_top_players_seconds_bucket[2s])) by (le,type))* 1000",
     "legendFormat": "p95 ({{type}})"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(leaderboard_get_top_players_seconds_bucket[2s])) by (le,type))* 1000",
     "legendFormat": "p99 ({{type}})"
    }
   ]
  },
  {
   "title": "Get Top Players Throughput (ops/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(leaderboard_get_top_players_seconds_count[2s])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Get Player Latency (p50/p95/p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(leaderboard_get_player_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "p50 ({{type}})"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(leaderboard_get_player_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "p95 ({{type}})"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(leaderboard_get_player_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "p99 ({{type}})"
    }
   ]
  },
  {
   "title": "Get Player Throughput (ops/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(leaderboard_get_player_seconds_count[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Get Player Rank Latency (p50/p95/p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(leaderboard_get_rank_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "p50 ({{type}})"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(leaderboard_get_rank_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "p95 ({{type}})"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(leaderboard_get_rank_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "p99 ({{type}})"
    }
   ]
  },
  {
   "title": "Get Player Rank Throughput (ops/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(leaderboard_get_rank_seconds_count[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Add Player Latency (p50/p95/p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(leaderboard_add_player_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "p50 ({{type}})"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(leaderboard_add_player_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "p95 ({{type}})"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(leaderboard_add_player_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "p99 ({{type}})"
    }
   ]
  },
  {
   "title": "Add Player Throughput (ops/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(leaderboard_add_player_seconds_count[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Bulk Add Players Latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum((leaderboard_add_players_bulk_seconds_sum \r\n/leaderboard_add_players_bulk_seconds_count)*1000) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Bulk Add Players Throughput (ops/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(leaderboard_add_players_bulk_seconds_count[2s])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Delete Player Latency (p50/p95/p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(leaderboard_delete_player_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "p50 ({{type}})"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(leaderboard_delete_player_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "p95 ({{type}})"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(leaderboard_delete_player_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "p99 ({{type}})"
    }
   ]
  },
  {
   "title": "Delete Player Throughput (ops/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(leaderboard_delete_player_seconds_count[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Delete All Players Latency (p50/p95/p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(leaderboard_delete_all_players_seconds_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "p50 ({{type}})"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(leaderboard_delete_all_players_seconds_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "p95 ({{type}})"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(leaderboard_delete_all_players_seconds_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "p99 ({{type}})"
    }
   ]
  },
  {
   "title": "Delete All Players Throughput (ops/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(leaderboard_delete_all_players_seconds_seconds_count[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}